project:
  type: website
  output-dir: docs

  preview:
    port: 22222
    browser: true
    watch-inputs: false
    navigate: true

  resources:
    - CNAME
    - pages/publications/srai-euroscipy-poster/poster.pdf
    - pages/publications/srai/srai_presentation.pdf
    - pages/publications/utilizing-osm-data-in-geospatial-representation-learning/OSMScience_2023.pdf
    - pages/publications/map-diffusion/map_generation_ai_acm.pdf

website:
  title: "Kraina AI"
  description: "Geospatial & Mobility Research Group at WUST"
  image: assets/kraina-logo.png
  favicon: assets/kraina-logo-favicon.png
  site-url: "https://kraina.ai"
  repo-url: https://github.com/kraina-ai/kraina-website

  twitter-card: true
  open-graph: true

  cookie-consent: true
  
  google-analytics:
    tracking-id: G-W8TQR5W028
    anonymize-ip: true

  navbar:
    logo: assets/kraina-logo.png

    left:
      - href: index.qmd
        icon: house
        text: Home
      - href: pages/news
        icon: body-text
        text: News
      - href: pages/team
        icon: people
        text: Team
      - href: pages/publications
        icon: files
        text: Publications
      - href: pages/contact
        icon: chat-square
        text: Contact

    tools:
      - icon: github
        text: Organization
        url: https://github.com/kraina-ai
      - icon: envelope
        aria-label: email
        text: contact@kraina.ai
        href: "mailto:contact@kraina.ai"

  page-footer:
    center: <span>🗺️ &#169; 2023  KRAINA CC BY 4.0 🗺️</span>
    border: True
    background: light

execute:
  enabled: true

editor:
  render-on-save: true

format:
  html:
    theme: # https://quarto.org/docs/output-formats/html-themes.html
      light:
        - cosmo
        - styles.scss
      # dark:
      #   - cyborg
      #   - styles.scss
    # toc: true
