name: Render and deploy Quarto files
on: 
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Render Book project
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: html

    - name: Publish HTML book
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
        render: false
